### ISSUE TITLE
Crash on opening attachment and hovering in inventory

### ISSUE THREAD

**Issue by abrossimow** [mortuusars/Exposure#128]
When opening the attachment menue in gamemode:creative and hovering over the inventory, the server instance crashes.
Full logs: https://mclo.gs/UiS2N6t

Fabric 0.16.7, MC 1.20.1
Exposure: 1.7.7

Can lead to ticking player entity, too. But could not reproduce regularly.
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-10-30 10:48:14
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at knot//net.minecraft.class_4558.method_22510(class_4558.java:60)
	at knot//net.minecraft.class_2066.method_24362(class_2066.java:55)
	at knot//net.minecraft.class_2066.method_8950(class_2066.java:51)
	at knot//net.minecraft.class_3222$2.method_7635(class_3222.java:252)
	at knot//net.minecraft.class_1703.method_34246(class_1703.java:219)
	at knot//net.minecraft.class_1703.method_7623(class_1703.java:176)
	at knot//net.minecraft.class_3222.method_5773(class_3222.java:472)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at knot//net.minecraft.class_4558.method_22510(class_4558.java:60)
	at knot//net.minecraft.class_2066.method_24362(class_2066.java:55)
	at knot//net.minecraft.class_2066.method_8950(class_2066.java:51)
	at knot//net.minecraft.class_3222$2.method_7635(class_3222.java:252)
	at knot//net.minecraft.class_1703.method_34246(class_1703.java:219)
	at knot//net.minecraft.class_1703.method_7623(class_1703.java:176)
	at knot//net.minecraft.class_3222.method_5773(class_3222.java:472)
	at knot//net.minecraft.class_3218.method_18762(class_3218.java:739)
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 5206
	Entity Name: ##
	Entity's Exact location: -88.41, 73.00, -1519.87
	Entity's Block location: World: (-89,73,-1520), Section: (at 7,9,0 in -6,4,-95; chunk contains blocks -96,-64,-1520 to -81,319,-1505), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,-64,-1536 to -1,319,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at knot//net.minecraft.class_1937.method_18472(class_1937.java:480)
	at knot//net.minecraft.class_3218.method_31420(class_3218.java:385)
	at knot//net.minecraft.class_5574.method_31791(class_5574.java:54)
	at knot//net.minecraft.class_3218.method_18765(class_3218.java:353)
	at knot//net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at knot//net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at knot//net.minecraft.class_1132.method_3748(class_1132.java:105)
	at knot//net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at knot//net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by mortuusars** [comment]
This is most likely caused by c2me. 
I've added a safeguard in 1.20.1-1.7.8 to potentially fix this particular crash, but haven't tested it myself. 
If the issue still happens - feel free to reopen this issue.
